spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  thymeleaf:
    cache: false

logging:
  level:
    root: warn
    com.personblog: info
  file:
    name: log/blog-dev.log
server:
  port: 8081