spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update

logging:
  level:
    root: info
    com.personblog: debug
  file:
    name: log/blog-dev.log